name: Notifications Cleaner

on:
  # Manual run → TEST (dry-run)
  workflow_dispatch:
    inputs:
      since:
        description: 'ISO8601 date (e.g. 2025-09-20T00:00:00Z). If empty, DAYS_BACK will be used'
        required: false
        default: ''
  # Release publish → APPLY (real mutations)
  release:
    types: [published]

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: read
      discussions: read
      pull-requests: read
      # Note: For notifications across all repos/orgs, a Personal Access Token with "notifications" scope is recommended.
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # ▶ Manual: TEST (dry-run only)
      - name: Dry-run on manual trigger
        if: ${{ github.event_name == 'workflow_dispatch' }}
        env:
          GITHUB_TOKEN: ${{ secrets.NOTIF_TOKEN }}
          INPUT_SINCE: ${{ inputs.since }}
          DAYS_BACK: '3'
          DRY_RUN: 'true'
          APPLY_CHANGES: 'false'
        run: node remove_phantom_notifications.cjs "${INPUT_SINCE}"

      # ▶ Auto on release: APPLY (real changes)
      - name: Apply on release
        if: ${{ github.event_name == 'release' }}
        env:
          GITHUB_TOKEN: ${{ secrets.NOTIF_TOKEN }}
          INPUT_SINCE: ''
          DAYS_BACK: '3'
          DRY_RUN: 'false'
          APPLY_CHANGES: 'true'
        run: node remove_phantom_notifications.cjs "${INPUT_SINCE}"